import { DestinationCatalogItem, TripDetails } from '@/types/itinerary';

export const COMPANY_DETAILS = {
  name: 'TRAVEL CARE TOURS Pvt Ltd',
  legalName: 'TRAVEL CARE TOURS PRIVATE LIMITED',
  tagline: 'Kerala Backwater & Hill Country Specialists',
  regNo: 'CIN: U63040KL2018PTC054231',
  addressLine1: 'Ground Flr, Mannath Bld,',
  addressLine2: '36/267 Seaport-Airport Rd,',
  addressLine3: 'Thrikkakara Ernakulam, Kerala - 682021',
  phone1: '+91 91435 43444',
  phone2: '+91 91435 43666',
  email: 'travelcare598@gmail.com',
  website: 'www.travelcaretours.in',
  gstin: '32AABCT8921K1ZX',
  pan: 'AANCT3052B',
  bankDetails: {
    bankName: 'HDFC',
    accountName: 'TRAVEL CARE TOURS PVT LTD',
    accountNumber: '50200118457708',
    ifscCode: 'HDFC0001286',
    branch: 'EDAPALLY',
    accountType: 'Current Account',
    upiId: 'Vyapar.175694334138@hdfcbank',
  },
};

export const INITIAL_DESTINATIONS_CATALOG: DestinationCatalogItem[] = [
  {
    destination: 'Munnar',
    tagline: 'Rolling Tea Gardens & Emerald Mountain Mist',
    description: 'Perched at 1,600m above sea level in the Western Ghats, Munnar is famous for verdant tea estates, exotic waterfalls, and rare flora.',
    defaultActivities: [
      {
        id: 'mun-1',
        title: 'Mattupetty Dam & Speed Boating',
        category: 'Nature',
        timing: 'Morning',
        description: 'Admire the tranquil reservoir surrounded by tea plantations with an exhilarating speed boat ride.',
      },
      {
        id: 'mun-2',
        title: 'Echo Point Scenic Stroll',
        category: 'Sightseeing',
        timing: 'Morning',
        description: 'Natural acoustic echo phenomenon set against misty hills and lakeside eucalyptus trees.',
      },
      {
        id: 'mun-3',
        title: 'Eravikulam National Park (Nilgiri Tahr Safari)',
        category: 'Nature',
        timing: 'Morning',
        description: 'Home to the endangered Nilgiri Tahr and rolling shola grasslands with panoramic vistas.',
      },
      {
        id: 'mun-4',
        title: 'Tata Tea Museum & Tea Processing Tour',
        category: 'Cultural',
        timing: 'Afternoon',
        description: 'Witness the century-old heritage of tea production and enjoy fresh tea leaf tasting sessions.',
      },
      {
        id: 'mun-5',
        title: 'Kundala Arch Dam & Pedal Boat Riding',
        category: 'Relaxation',
        timing: 'Afternoon',
        description: 'Asia’s first arch dam with picturesque cherry blossom trees and peaceful Shikara-style pedal boats.',
      },
      {
        id: 'mun-6',
        title: 'Cheeyappara & Valara Waterfalls Photo Stop',
        category: 'Nature',
        timing: 'Morning',
        description: 'Cascading seven-step waterfalls nestled right on the scenic Kochi-Munnar hill highway.',
      },
      {
        id: 'mun-7',
        title: 'Blossom Hydel Park & Flower Garden',
        category: 'Relaxation',
        timing: 'Evening',
        description: 'Vibrant landscaped flowerbeds, rope walks, and evening campfire viewpoints along the river.',
      },
      {
        id: 'mun-8',
        title: 'Pothamedu View Point Sunset',
        category: 'Sightseeing',
        timing: 'Evening',
        description: 'Spectacular sunset vantage point overlooking sprawling valleys blanketed in tea and cardamom.',
      },
    ],
  },
  {
    destination: 'Thekkady',
    tagline: 'Periyar Tiger Reserve & Fragrant Spices',
    description: 'Set around the Periyar Wildlife Sanctuary, Thekkady offers boat safaris on Periyar Lake, spice plantations, and Kerala martial arts.',
    defaultActivities: [
      {
        id: 'thek-1',
        title: 'Periyar Lake Wildlife Boat Safari',
        category: 'Nature',
        timing: 'Morning',
        description: 'Scenic boat ride across the sunken forest reservoir with chances to spot wild elephants, gaur, and exotic water birds.',
      },
      {
        id: 'thek-2',
        title: 'Guided Spice Plantation Walking Tour',
        category: 'Cultural',
        timing: 'Afternoon',
        description: 'Aromatic walk exploring fresh cardamom, black pepper, cinnamon, vanilla, cloves, and nutmeg cultivation.',
      },
      {
        id: 'thek-3',
        title: 'Kalaripayattu Martial Arts Live Show',
        category: 'Cultural',
        timing: 'Evening',
        description: 'Witness India’s oldest martial arts discipline featuring breathtaking acrobatics, swordplay, and fire leaps.',
      },
      {
        id: 'thek-4',
        title: 'Kathakali Classical Dance Performance',
        category: 'Cultural',
        timing: 'Evening',
        description: 'Traditional Kerala dance-drama with intricate facial make-up, expressive mudras, and vivid storytelling.',
      },
      {
        id: 'thek-5',
        title: 'Elephant Junction Ride & Bathing Experience',
        category: 'Adventure',
        timing: 'Afternoon',
        description: 'Interactive elephant interaction, jungle timber rides, and bathing session with gentle giants.',
      },
      {
        id: 'thek-6',
        title: 'Kumily Spice & Handicraft Market Shopping',
        category: 'Shopping',
        timing: 'Evening',
        description: 'Direct procurement of export-grade spices, cold-pressed oils, handmade soaps, and Kerala banana chips.',
      },
    ],
  },
  {
    destination: 'Alleppey',
    tagline: 'The Venice of the East & Backwater Houseboats',
    description: 'A labyrinth of shimmering canals, tranquil lagoons, emerald paddy fields, and traditional Kerala Kettuvallam houseboats.',
    defaultActivities: [
      {
        id: 'all-1',
        title: 'Traditional Deluxe/Premium Houseboat Cruise',
        category: 'Relaxation',
        timing: 'Full Day',
        description: 'Check-in to private thatched-roof Kettuvallam at 12:00 PM. Glide along palm-fringed canals with freshly prepared Kerala Karimeen lunch on board.',
      },
      {
        id: 'all-2',
        title: 'Village Canoe (Shikara) Tour in Narrow Canals',
        category: 'Cultural',
        timing: 'Morning',
        description: 'Quiet wooden canoe ride through narrow village waterways to observe coir making, duck farming, and local life.',
      },
      {
        id: 'all-3',
        title: 'Alleppey Beach & Old Sea Pier Walk',
        category: 'Sightseeing',
        timing: 'Evening',
        description: 'Historic beach featuring a 150-year-old colonial pier jutting out into the Arabian Sea and sweeping sunset views.',
      },
      {
        id: 'all-4',
        title: 'Alappuzha Lighthouse Visit',
        category: 'Heritage',
        timing: 'Afternoon',
        description: 'Climb the spiral stairs of the striped heritage lighthouse for a 360-degree view of the Arabian sea and lush coastal canopy.',
      },
      {
        id: 'all-5',
        title: 'Sunset Cruise on Punnamada Lake',
        category: 'Relaxation',
        timing: 'Evening',
        description: 'Site of the world-famous Nehru Trophy Snake Boat Race; gentle breezes as the sun dips into the water.',
      },
    ],
  },
  {
    destination: 'Kovalam',
    tagline: 'Golden Crescent Beaches & Lighthouse Vistas',
    description: 'World-renowned coastal haven famous for crescent-shaped sandy beaches, lighthouse promontory, and soothing Ayurvedic therapies.',
    defaultActivities: [
      {
        id: 'kov-1',
        title: 'Lighthouse Beach & Spiral Tower Climb',
        category: 'Sightseeing',
        timing: 'Morning',
        description: 'The iconic 30m high Vizhinjam Lighthouse with panoramic views of the rocky coastline and breaking waves.',
      },
      {
        id: 'kov-2',
        title: 'Hawa Beach & Coastal Promenade Stroll',
        category: 'Relaxation',
        timing: 'Afternoon',
        description: 'Scenic bay known for catamarans, early morning fisherman hauls, and gentle coastal cafes.',
      },
      {
        id: 'kov-3',
        title: 'Samudra Beach Relaxation & Sunset',
        category: 'Relaxation',
        timing: 'Evening',
        description: 'Peaceful northern stretch away from bustling crowds, ideal for reading and watching traditional wooden catamarans.',
      },
      {
        id: 'kov-4',
        title: 'Traditional Ayurvedic Rejuvenation Massage',
        category: 'Relaxation',
        timing: 'Afternoon',
        description: 'Authentic Kerala herbal oil body massage by certified therapists to relieve travel fatigue.',
      },
      {
        id: 'kov-5',
        title: 'Vizhinjam Marine Aquarium & Rock-Cut Cave',
        category: 'Sightseeing',
        timing: 'Morning',
        description: 'Exotic marine life exhibits and ancient 8th-century granite cave temple dedicated to Vinadhara Dakshinamurti.',
      },
    ],
  },
  {
    destination: 'Kanyakumari',
    tagline: 'Lands End: Meeting of Three Seas',
    description: 'The southernmost tip of the Indian peninsula where the Arabian Sea, Indian Ocean, and Bay of Bengal converge.',
    defaultActivities: [
      {
        id: 'kan-1',
        title: 'Vivekananda Rock Memorial Ferry & Temple',
        category: 'Heritage',
        timing: 'Morning',
        description: 'Iconic offshore rock monument built in 1970 where Swami Vivekananda attained spiritual enlightenment.',
      },
      {
        id: 'kan-2',
        title: 'Thiruvalluvar 133-ft Stone Statue',
        category: 'Heritage',
        timing: 'Morning',
        description: 'Towering monumental tribute to the venerable Tamil poet and philosopher on an adjoining sea rock.',
      },
      {
        id: 'kan-3',
        title: 'Triveni Sangam Holy Dip & Beach Walk',
        category: 'Cultural',
        timing: 'Morning',
        description: 'The sacred confluence point where three ocean currents meet with distinct shades of water.',
      },
      {
        id: 'kan-4',
        title: 'Sunset View Point at Lands End',
        category: 'Sightseeing',
        timing: 'Evening',
        description: 'Fabled spot to witness sunset over the open ocean, with simultaneous moonrise during full moon days.',
      },
      {
        id: 'kan-5',
        title: 'Padmanabhapuram Palace Heritage Tour (En-route)',
        category: 'Heritage',
        timing: 'Afternoon',
        description: 'Magnificent 16th-century wooden palace displaying exquisite Kerala architectural woodwork and antique royal halls.',
      },
    ],
  },
  {
    destination: 'Kochi (Cochin)',
    tagline: 'Queen of the Arabian Sea & Historic Fort Kochi',
    description: 'Gateway to Kerala with 600 years of global trade heritage, Dutch palaces, Jewish synagogues, and iconic Chinese fishing nets.',
    defaultActivities: [
      {
        id: 'koc-1',
        title: 'Chinese Fishing Nets (Cheena Vala) at Fort Kochi Beach',
        category: 'Heritage',
        timing: 'Morning',
        description: 'Centuries-old shore-operated cantilever fishing nets introduced by 14th-century Chinese traders.',
      },
      {
        id: 'koc-2',
        title: 'Mattancherry Palace (Dutch Palace) & Royal Murals',
        category: 'Heritage',
        timing: 'Morning',
        description: 'Built by the Portuguese in 1555 and renovated by the Dutch; houses world-famous Hindu mythological murals.',
      },
      {
        id: 'koc-3',
        title: 'Paradesi Synagogue & Jew Town Antique Walk',
        category: 'Cultural',
        timing: 'Afternoon',
        description: 'Oldest active synagogue in the Commonwealth (1568) with hand-painted Belgian chandeliers and Willow-pattern tiles.',
      },
      {
        id: 'koc-4',
        title: 'St. Francis Church (Vasco da Gama Tomb Site)',
        category: 'Heritage',
        timing: 'Afternoon',
        description: 'Oldest European-built church in India where legendary explorer Vasco da Gama was originally buried.',
      },
      {
        id: 'koc-5',
        title: 'Marine Drive Sunset Cruise & Shopping',
        category: 'Shopping',
        timing: 'Evening',
        description: 'Scenic promenade overlooking the Cochin backwaters, Kochi harbour container terminal, and bustling night markets.',
      },
    ],
  },
  {
    destination: 'Wayanad',
    tagline: 'Misty Highlands, Caves & Waterfalls',
    description: 'Enchanting hill district situated in the northeast of Kerala featuring pre-historic caves, dense rainforests, and treehouse retreats.',
    defaultActivities: [
      {
        id: 'way-1',
        title: 'Edakkal Caves Neolithic Stone Petroglyphs',
        category: 'Heritage',
        timing: 'Morning',
        description: 'Historic rock shelters situated at 1,200m altitude containing rare petroglyphic engravings dating to 6,000 BCE.',
      },
      {
        id: 'way-2',
        title: 'Banasura Sagar Dam Speed Boating',
        category: 'Nature',
        timing: 'Afternoon',
        description: 'Largest earthen dam in India and second largest in Asia, surrounded by forested islands.',
      },
      {
        id: 'way-3',
        title: 'Soochipara (Sentinel Rock) Waterfalls Trek',
        category: 'Adventure',
        timing: 'Morning',
        description: 'Three-tiered spectacular waterfall cascading into a natural pool surrounded by dense deciduous jungle.',
      },
      {
        id: 'way-4',
        title: 'Pookode Natural Freshwater Lake & Pedal Boating',
        category: 'Relaxation',
        timing: 'Evening',
        description: 'Nestled between evergreen forests and western ghats with blue water lilies and an aquarium.',
      },
    ],
  },
];

export const SAMPLE_TRIP: TripDetails = {
  id: 'trip-tct-0195',
  voucherNumber: 'TCT-2026-KER-0195',
  tripTitle: 'KERALA SCENIC ESCAPE',
  guestName: 'Valued Guest',
  guestContact: '',
  guestEmail: 'travelcare598@gmail.com',
  adultsCount: 2,
  childrenCount: 1,
  childrenAges: '3yr old',
  durationDays: 7,
  durationNights: 6,
  pickupDate: '19th Sept 2026',
  pickupTime: '09:30 AM',
  pickupLocation: 'Kochi Airport (COK)',
  dropoffDate: '25th Sept 2026',
  dropoffTime: '05:00 PM',
  dropoffLocation: 'Kochi / Trivandrum Airport',
  routeSummary: 'Kochi → Munnar → Thekkady → Alleppey → Kovalam → Kanyakumari → Kochi',
  vehicleType: 'AC Sedan',
  vehicleNotes: 'Dedicated sanitized air-conditioned sedan with courteous, professional tourist chauffeur. All tolls, parking, interstate road permits, fuel, and driver allowances included throughout the trip.',
  totalPackageCost: '₹81,000.00',
  costTerms: 'Total package cost inclusive of private transportation, accommodation, meal plan & mentioned sightseeing.',
  advancePaid: '₹ 0/-',
  balancePayable: '₹81,000.00',
  bookingStatus: 'Under Review',
  specialNotes: 'All sightseeing is subject to weather, local regulations, road conditions and attraction operating schedules. Houseboat check-in, cruise duration, meal plan and mooring point depend on the selected operator and operational conditions.',
  vehicleCharge: 14500,
  marginType: 'percentage',
  marginPercent: 20,
  marginCustomAmount: 6000,
  adjustmentAmount: 0,
  inclusions: [
    '01 Sanitized AC Sedan at disposal as per itinerary from arrival to departure',
    'Chauffeur allowances, driver bata, fuel charges, and parking fees (Tolls payable directly)',
    '02 Nights accommodation at The Leaf Munnar (Green Leaf Room)',
    '01 Night accommodation at Pepper Vine Thekkady (Delux Room)',
    '01 Night private Premium Houseboat cruise at Alleppey with all meals',
    '02 Nights accommodation at Aadisaktthi Leisure Resort Kovalam (Delux Room)',
    'Meal Plan: CP (Buffet Breakfast) at hotels/resorts; all meals on Houseboat',
    'Traditional welcome drink on arrival at all hotels',
    '24/7 dedicated Travel Care Tours customer service helpline & local manager support',
  ],
  exclusions: [
    'Toll gate charges (payable directly by guest)',
    'Airfare / Train tickets to and from Kerala',
    'Entry tickets to monuments, Eravikulam National park bus, boat tickets, and elephant activities',
    'Optional activities and entry tickets are payable directly unless specifically included',
    'Personal expenses such as laundry, phone calls, room service, alcoholic beverages, and tips',
    'Extra charges may apply for A/C when running in hill areas or heaters if required',
  ],
  accommodations: [
    {
      id: 'acc-1',
      destination: 'Munnar',
      hotelName: 'The Leaf',
      roomCategory: 'Green Leaf',
      checkInDate: '19th Sept 2026',
      nights: 1,
      mealPlan: 'CP (Buffet Breakfast)',
      status: 'Confirmed',
      b2bPrice: 3200,
      b2bTotal: 3200,
    },
    {
      id: 'acc-2',
      destination: 'Munnar',
      hotelName: 'The Leaf',
      roomCategory: 'Green Leaf',
      checkInDate: '20th Sept 2026',
      nights: 1,
      mealPlan: 'CP (Buffet Breakfast)',
      status: 'Confirmed',
      b2bPrice: 3200,
      b2bTotal: 3200,
    },
    {
      id: 'acc-3',
      destination: 'Thekkady',
      hotelName: 'Pepper Vine',
      roomCategory: 'Delux',
      checkInDate: '21st Sept 2026',
      nights: 1,
      mealPlan: 'CP (Buffet Breakfast)',
      status: 'Confirmed',
      b2bPrice: 2800,
      b2bTotal: 2800,
    },
    {
      id: 'acc-4',
      destination: 'Alleppey',
      hotelName: 'Houseboat',
      roomCategory: 'Premium Room',
      checkInDate: '22nd Sept 2026',
      nights: 1,
      mealPlan: 'Houseboat All Meals Plan',
      status: 'Confirmed',
      b2bPrice: 7500,
      b2bTotal: 7500,
    },
    {
      id: 'acc-5',
      destination: 'Kovalam',
      hotelName: 'Aadisaktthi Leisure Resort',
      roomCategory: 'Delux Room',
      checkInDate: '23rd Sept 2026',
      nights: 1,
      mealPlan: 'CP (Buffet Breakfast)',
      status: 'Confirmed',
      b2bPrice: 2900,
      b2bTotal: 2900,
    },
    {
      id: 'acc-6',
      destination: 'Kovalam',
      hotelName: 'Aadisaktthi Leisure Resort',
      roomCategory: 'Delux Room',
      checkInDate: '24th Sept 2026',
      nights: 1,
      mealPlan: 'CP (Buffet Breakfast)',
      status: 'Confirmed',
      b2bPrice: 2900,
      b2bTotal: 2900,
    },
  ],
  days: [
    {
      dayNumber: 1,
      date: '19th Sept 2026',
      title: 'ARRIVAL IN KOCHI → MUNNAR',
      destination: 'Munnar',
      overnightStay: 'The Leaf Munnar Resort',
      route: 'Kochi Airport pickup and private transfer to Munnar',
      summary: 'Arrive at Kochi and begin your scenic journey towards Munnar, Kerala’s famous hill station. Enjoy lush plantations, winding mountain roads, waterfalls and cool misty landscapes.',
      mealsIncluded: 'Dinner at Resort',
      activities: [
        {
          id: 'act-1-1',
          title: 'Kochi Airport pickup and private transfer to Munnar.',
          category: 'Sightseeing',
          timing: 'Morning',
          description: 'Meet and greet by your chauffeur followed by scenic drive.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-2',
          title: 'Cheeyappara Waterfalls – refreshing scenic stop on the Munnar route.',
          category: 'Nature',
          timing: 'Morning',
          description: 'Multi-tiered waterfall alongside the highway.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-3',
          title: 'Valara Waterfalls – picturesque waterfall surrounded by lush greenery.',
          category: 'Nature',
          timing: 'Afternoon',
          description: 'Stunning rainforest cascade view.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-4',
          title: 'Spices Plantation – experience Kerala’s aromatic spice-growing region.',
          category: 'Cultural',
          timing: 'Afternoon',
          description: 'Cardamom, pepper, cinnamon and clove plants.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-5',
          title: 'Flora & Fauna Munnar Eco Park – nature and family-friendly scenic stop. (optional)',
          category: 'Nature',
          timing: 'Afternoon',
          description: 'Botanical flora display and eco trails.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-6',
          title: 'Experience eco-adventure thrills and family-friendly rides at Wonder Valley Adventure and Amusement Park amidst Munnar\'s misty hills. (optional)',
          category: 'Adventure',
          timing: 'Afternoon',
          description: 'Valley theme park with family attractions.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-7',
          title: 'Pass through tea, spice and cardamom-growing landscapes on the way to Munnar.',
          category: 'Nature',
          timing: 'Afternoon',
          description: 'Scenic high range road vistas.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-1-8',
          title: 'Evening at leisure to enjoy the mountain ambience.',
          category: 'Relaxation',
          timing: 'Evening',
          description: 'Relax at resort amidst the hills.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 2,
      date: '20th Sept 2026',
      title: 'MUNNAR SIGHTSEEING – TEA COUNTRY & SCENIC HIGHLIGHTS',
      destination: 'Munnar',
      overnightStay: 'The Leaf Munnar Resort',
      route: 'Munnar Local Sightseeing Circuit',
      summary: 'Explore the scenic highlands of Munnar with waterfalls, tea country, gardens and mountain viewpoints.',
      mealsIncluded: 'Breakfast & Dinner',
      activities: [
        {
          id: 'act-2-1',
          title: 'Tea Museum – discover Munnar’s tea-growing heritage, subject to opening.',
          category: 'Cultural',
          timing: 'Morning',
          description: 'Historic artifacts and demonstration of tea processing.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-2-2',
          title: 'Eravikulam National Park – visit the high-altitude grasslands and mountain scenery, subject to park opening and local conditions.',
          category: 'Nature',
          timing: 'Morning',
          description: 'Home of the Nilgiri Tahr and Anamudi Peak vistas.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-2-3',
          title: 'Flower Garden / Botanical Garden and Munnar Gap Road – scenic local sightseeing.',
          category: 'Sightseeing',
          timing: 'Afternoon',
          description: 'Manicured flower beds and photography point.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-2-4',
          title: 'Lockhart Gap View/ Mattupetty Dam, Eco Point',
          category: 'Nature',
          timing: 'Afternoon',
          description: 'Scenic lake reservoir and natural echo phenomena.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 3,
      date: '21st Sept 2026',
      title: 'MUNNAR → THEKKADY – WILDLIFE & CULTURAL EXPERIENCE',
      destination: 'Thekkady',
      overnightStay: 'PepperVine, Thekkady',
      route: 'Munnar to Thekkady (Kumily) scenic drive',
      summary: 'Depart Munnar after breakfast and travel through the lush Western Ghats towards Thekkady.',
      mealsIncluded: 'Breakfast & Dinner',
      activities: [
        {
          id: 'act-3-1',
          title: 'Elephant Ride & Bath – optional activity, subject to availability.',
          category: 'Adventure',
          timing: 'Morning',
          description: 'Elephant interaction in a jungle setting.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-3-2',
          title: 'Boating in Periyar Tiger Reserve – optional activity, subject to availability.',
          category: 'Nature',
          timing: 'Afternoon',
          description: 'Boat ride on Periyar Lake inside the national park.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-3-3',
          title: 'Jeep Safari – optional activity, subject to availability.',
          category: 'Adventure',
          timing: 'Afternoon',
          description: 'Off-road exploration through cardamom forests.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-3-4',
          title: 'Tamil Nadu / Sathram sightseeing – optional, subject to time and local conditions.',
          category: 'Sightseeing',
          timing: 'Afternoon',
          description: 'Scenic vantage point on the Kerala-Tamil Nadu border.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-3-5',
          title: 'Kadhakali & Kalaripayattu Show (5:00 PM – 8:00 PM) – evening cultural experience.',
          category: 'Cultural',
          timing: 'Evening',
          description: 'Traditional Kerala classical art form and martial arts display.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 4,
      date: '22nd Sept 2026',
      title: 'THEKKADY → ALLEPPEY – PREMIUM HOUSEBOAT EXPERIENCE',
      destination: 'Alleppey',
      overnightStay: 'Houseboat, Alleppey',
      route: 'Thekkady to Alleppey (Alappuzha) backwaters',
      summary: 'After breakfast, proceed to Alleppey (Alappuzha) and board your houseboat for a relaxing backwater experience.',
      mealsIncluded: 'Houseboat Lunch, Evening Snacks, Dinner & Breakfast',
      activities: [
        {
          id: 'act-4-1',
          title: 'Board the Premium Houseboat and begin the cruise.',
          category: 'Relaxation',
          timing: 'Morning',
          description: 'Check in at 12:00 PM with tender coconut welcome drink.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-4-2',
          title: 'Houseboating All Day with food and stay on board.',
          category: 'Relaxation',
          timing: 'Full Day',
          description: 'Leisurely glide across Vembanad lake and tranquil backwaters.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-4-3',
          title: 'Cruise through canals, paddy fields, lagoons and traditional Kerala villages.',
          category: 'Cultural',
          timing: 'Afternoon',
          description: 'Picturesque rural backwater life and palm fringes.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-4-4',
          title: 'Enjoy meals on board according to the houseboat meal plan.',
          category: 'Cultural',
          timing: 'Afternoon',
          description: 'Freshly prepared traditional Kerala cuisine on board.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-4-5',
          title: 'Alappuzha Beach and Lighthouse – visit subject to time.',
          category: 'Sightseeing',
          timing: 'Evening',
          description: 'Seaside sunset and historic beach pier.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 5,
      date: '23rd Sept 2026',
      title: 'ALLEPPEY → KOVALAM – COASTAL ESCAPE',
      destination: 'Kovalam',
      overnightStay: 'Aadisaktthi Leisure Resort Kovalam',
      route: 'Alleppey to Kovalam beach road',
      summary: 'After breakfast, disembark from the houseboat as per the operator schedule and proceed towards Kovalam.',
      mealsIncluded: 'Houseboat Breakfast & Resort Dinner',
      activities: [
        {
          id: 'act-5-1',
          title: 'Kovalam Beach / Lighthouse – if time permits.',
          category: 'Sightseeing',
          timing: 'Afternoon',
          description: 'Iconic spiral-striped lighthouse and Arabian Sea view.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-5-2',
          title: 'Relax by the beach and enjoy the coastal ambience.',
          category: 'Relaxation',
          timing: 'Evening',
          description: 'Sunset promenade along the sandy cove.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-5-3',
          title: 'Check-in at Uday Samudra Leisure Beach Hotel, Kovalam.',
          category: 'Relaxation',
          timing: 'Evening',
          description: 'Resort check-in and leisure.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 6,
      date: '24th Sept 2026',
      title: 'KOVALAM → KANYAKUMARI',
      destination: 'Kanyakumari',
      overnightStay: 'Aadisaktthi Leisure Resort Kovalam',
      route: 'Kovalam to Kanyakumari coastal excursion & return',
      summary: 'Proceed from Kovalam to Kanyakumari and enjoy the iconic coastal landmarks of India’s southern tip.',
      mealsIncluded: 'Breakfast & Dinner',
      activities: [
        {
          id: 'act-6-1',
          title: 'Poovar Island – optional visit.',
          category: 'Sightseeing',
          timing: 'Morning',
          description: 'Boat cruise through mangroves to golden sand beach.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-2',
          title: 'Azhimala Shiva Temple – scenic coastal temple stop.',
          category: 'Cultural',
          timing: 'Morning',
          description: 'Gigantic cliffside Shiva sculpture overlooking the sea.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-3',
          title: 'Vivekananda Rock Memorial – visit subject to ferry / weather conditions.',
          category: 'Heritage',
          timing: 'Afternoon',
          description: 'Offshore monument where Swami Vivekananda meditated.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-4',
          title: 'Arulmigu Devi Temple – temple visit.',
          category: 'Cultural',
          timing: 'Afternoon',
          description: 'Sacred seashore shrine of Goddess Kanya Kumari.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-5',
          title: 'Thiruvalluvar Statue and Triveni Sangam – iconic Kanyakumari landmarks.',
          category: 'Heritage',
          timing: 'Afternoon',
          description: 'Meeting point of three seas: Arabian Sea, Indian Ocean, Bay of Bengal.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-6',
          title: 'Gandhi Mandapam – historical memorial.',
          category: 'Heritage',
          timing: 'Evening',
          description: 'Architectural memorial overlooking the waters.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-6-7',
          title: 'Return back to Kovalam for stay.',
          category: 'Relaxation',
          timing: 'Night',
          description: 'Overnight rest at Kovalam resort.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
    {
      dayNumber: 7,
      date: '25th Sept 2026',
      title: 'KOVALAM → KOCHI',
      destination: 'Departure',
      overnightStay: 'Tour Ends with Beautiful Kerala Memories',
      route: 'Kovalam to Kochi / Trivandrum Airport drop',
      summary: 'Sree Padmanabhaswamy Temple visit – subject to flight timing and check out. Tour Ends with Beautiful Kerala Memories.',
      mealsIncluded: 'Breakfast',
      activities: [
        {
          id: 'act-7-1',
          title: 'Sree Padmanabhaswamy Temple visit – subject to flight timing and check out.',
          category: 'Cultural',
          timing: 'Morning',
          description: 'World-renowned architectural marvel in Thiruvananthapuram.',
          isSelected: true,
          isVerified: true,
        },
        {
          id: 'act-7-2',
          title: 'Tour Ends with Beautiful Kerala Memories.',
          category: 'Sightseeing',
          timing: 'Afternoon',
          description: 'Chauffeur drop at airport or railway station.',
          isSelected: true,
          isVerified: true,
        },
      ],
    },
  ],
  createdAt: '2026-09-03T10:00:00.000Z',
  updatedAt: '2026-09-03T10:00:00.000Z',
};

export const DEFAULT_KERALA_DESTINATIONS = [
  'Munnar',
  'Thekkady',
  'Alleppey',
  'Kovalam',
  'Cochin',
  'Kumarakom',
  'Wayanad',
  'Kanyakumari',
  'Poovar',
  'Athirappilly',
  'Varkala',
  'Marari',
];

export const LOCATION_OPTIONS = [
  'Cochin International Airport (COK)',
  'Thiruvananthapuram International Airport (TRV)',
  'Ernakulam Railway Station',
  'Trivandrum Railway Station',
  'Cochin',
  'Thiruvananthapuram',
];

export const VEHICLE_OPTIONS = [
  'AC Sedan',
  'AC SUV',
  'Traveller 12 Seater AC',
];

export const MEAL_PLAN_OPTIONS = [
  'CP (Buffet Breakfast)',
  'MAP (Breakfast & Dinner)',
  'AP (All Meals)',
  'EP (Room Only)',
];

export const HOTEL_SUGGESTIONS: Record<string, string[]> = {
  Munnar: ['The Leaf Munnar Resort', 'Tea County', 'Tall Trees Resort', 'Amber Dale', 'Fragrant Nature Munnar', 'Spice Tree Munnar'],
  Thekkady: ['Pepper Vine Hotel', 'The Elephant Court', 'Spice Village - CGH Earth', 'Greenwoods Resort', 'Cardamom County'],
  Alleppey: ['Private Premium AC Houseboat', 'Lakes & Lagoons Houseboat', 'Ramada by Wyndham Alleppey', 'UDS Backwater Resort'],
  Kovalam: ['Aadisaktthi Leisure Resort', 'Uday Samudra Leisure Beach Hotel', 'The Leela Kovalam', 'Turtle on the Beach', 'Gokulam Grand'],
  Cochin: ['Trident Cochin', 'Brunton Boatyard - CGH Earth', 'Fragrant Nature Kochi', 'Grand Hyatt Kochi Bolgatty'],
  Kumarakom: ['Whispering Palms Lake Resort', 'Kumarakom Lake Resort', 'Zuri Kumarakom', 'Coconut Lagoon - CGH Earth'],
  Wayanad: ['Morickap Resort', 'Vythiri Resort', 'Windflower Resort', 'Arayal Resorts Wayanad'],
  Kanyakumari: ['Sparsa Resort', 'Annai Resorts & Spa', 'Hotel Sea View'],
  Poovar: ['Poovar Island Resort', 'Estuary Sarovar Portico', 'Isola Di Cocco'],
  Athirappilly: ['Rainforest Resort Athirappilly', 'Casa Rio Resort'],
  Varkala: ['Gateway Hotel Varkala', 'Clafouti Beach Resort', 'BCM Touring Club'],
  Marari: ['Marari Beach Resort - CGH Earth', 'Abad Turtle Beach', 'Carnoustie Ayurveda & Wellness Resort'],
};

