name: Push Planner to Website Repo

on:
  push:
    branches:
      - main

jobs:
  copy-to-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Planner Repo
        uses: actions/checkout@v4

      - name: Push Files to Website Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '.'     
          destination_repo: 'travelcare-tours/website'
          destination_folder: 'planner'
          user_email: 'travelcare598@gmail.com' # Replace with your GitHub email if different
          user_name: 'travelcare-tours'
          commit_message: 'Automated update from Planner repo via GitHub Actions'
